server:
  port: 8091
spring:
  cloud:
    gateway:
      routes:
        - id: review-service
          uri: http://localhost:8082
          predicates:
            - Path=/customerRatingReview/**
        - id: product-service
          uri: http://localhost:8111
          predicates:
            - Path=/product/**
        - id: payment-service
          uri: http://localhost:8089
          predicates:
            - Path=/payment/**
        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=/order/**
            - Path=/cart/**
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
            - Path=/address/**
        - id: webapp
          uri: http://localhost:4200
          predicates:
            - Path=/webapp/**

#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin




